# Site settings
title: Rhythm.Vision
email: kyle@kylegrover.com
description: > 
  Rhythm.Vision is the home of all Kyle Grover's Video Fuckery, Audio Fuckery, and - most importantly - A/V Fuckery
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rhythm.vision" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
facebook_username: rhythmdotvision
instagram_username: rhythm.vision
port: 1234

# Build settings
markdown: kramdown
